services:
  - type: web
    name: vite-app
    env: node
    buildCommand: npm run build
    startCommand: npx serve dist
    staticAssets:
      rewrites:
        - source: /(.*) # match any path
          destination: / # serve index.html
